// GENERATED by scripts/build-catalog.mjs from YouCam's hair-transfer v2.1 template list.
// Edit the table in that script and re-run it; do not edit this file by hand.
import type { Collection, TargetStyle } from "./types.ts";
import { routeHintsFor } from "./hints.ts";

type Row = Omit<TargetStyle, "routeHints">;

const ROWS: Row[] = [
  {
    "id": "buzz-cut",
    "name": "Buzz cut",
    "description": "Clipper cut all over, one short length.",
    "templateId": "all_buzz_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_buzz_cut.jpg",
      "salon": "/styles/salon/all_buzz_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "low",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "soft-buzz-cut",
    "name": "Soft buzz cut",
    "description": "Very short all over with a softer outline.",
    "templateId": "female_buzz_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_buzz_cut.jpg",
      "salon": "/styles/salon/female_buzz_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "low",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "crew-cut",
    "name": "Crew cut",
    "description": "Short, tapered sides with a little length on top.",
    "templateId": "all_crewcut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_crewcut.jpg",
      "salon": "/styles/salon/all_crewcut.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "above_ears",
    "maintenance": "low",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "changes hair colour"
    ]
  },
  {
    "id": "textured-crew-cut",
    "name": "Textured crew cut",
    "description": "Neat crew cut with light texture on top.",
    "templateId": "female_crewcut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_crewcut.jpg",
      "salon": "/styles/salon/female_crewcut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "low",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "messy-tapered-fade",
    "name": "Messy tapered fade",
    "description": "Faded sides with a loose, messy top.",
    "templateId": "all_messy_tapered_fade",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_messy_tapered_fade.jpg",
      "salon": "/styles/salon/all_messy_tapered_fade.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "low",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "changes hair colour"
    ]
  },
  {
    "id": "taper-fade",
    "name": "Taper fade",
    "description": "Gradual taper at the sides and back.",
    "templateId": "male_gray_taper_fade",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_gray_taper_fade.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "changes hair colour"
    ]
  },
  {
    "id": "textured-crop",
    "name": "Textured crop",
    "description": "Short, choppy top with a fringe that falls forward.",
    "templateId": "male_textured_crop",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_textured_crop.jpg",
      "salon": "/styles/salon/male_textured_crop.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "low",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe",
      "changes hair colour"
    ]
  },
  {
    "id": "short-curly-top",
    "name": "Short curly top",
    "description": "Short sides with defined curls on top.",
    "templateId": "male_short_curly",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_short_curly.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "low",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "curly",
    "sideEffects": [
      "changes hair colour"
    ]
  },
  {
    "id": "textured-comma",
    "name": "Textured comma",
    "description": "Short sides with a curved comma fringe.",
    "templateId": "male_textured_comma",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_textured_comma.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "wavy",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "side-swept-undercut",
    "name": "Side-swept undercut",
    "description": "Disconnected short sides, longer top swept over.",
    "templateId": "all_side_swept_undercut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_side_swept_undercut.jpg",
      "salon": "/styles/salon/all_side_swept_undercut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "wavy-undercut",
    "name": "Wavy undercut",
    "description": "Short sides with a wavy, longer top.",
    "templateId": "male_wavy_undercut",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_wavy_undercut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "combover",
    "name": "Combover",
    "description": "Short sides with the top combed to one side.",
    "templateId": "female_combover",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_combover.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "low",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "tousled-cut",
    "name": "Tousled cut",
    "description": "Loose, layered cut sitting around the ears.",
    "templateId": "male_tousled_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_tousled_cut.jpg",
      "salon": "/styles/salon/male_tousled_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "ear_length",
    "maintenance": "low",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "full-afro",
    "name": "Full afro",
    "description": "Full, rounded afro with a shaped outline.",
    "templateId": "male_afro",
    "collections": [
      "barbershop"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/male_afro.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "coily",
    "sideEffects": []
  },
  {
    "id": "tousled-waves",
    "name": "Tousled waves",
    "description": "Wavy, grown-in cut reaching the jaw.",
    "templateId": "all_tousled_waves",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_tousled_waves.jpg",
      "salon": "/styles/salon/all_tousled_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "grown-out-waves",
    "name": "Grown-out waves",
    "description": "Grown-out waves falling past the shoulders.",
    "templateId": "all_hippie_wave",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_hippie_wave.jpg",
      "salon": "/styles/salon/all_hippie_wave.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "locs",
    "name": "Locs",
    "description": "Locs: a long-term commitment started and maintained by a specialist.",
    "templateId": "all_dreadlocks",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "barbershop",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_dreadlocks.jpg",
      "salon": "/styles/salon/all_dreadlocks.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "pixie",
    "name": "Pixie",
    "description": "Short, soft pixie with texture on top.",
    "templateId": "all_pixie",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_pixie.jpg",
      "salon": "/styles/salon/all_pixie.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_ears",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "wispy-fringe-pixie",
    "name": "Wispy fringe pixie",
    "description": "Ear-length pixie with a soft, wispy fringe.",
    "templateId": "all_wispy_fringe_pixie",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_wispy_fringe_pixie.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "ear_length",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "bixie-cut",
    "name": "Bixie cut",
    "description": "Between a bob and a pixie, around the ears.",
    "templateId": "all_bixie_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_bixie_cut.jpg",
      "salon": "/styles/salon/all_bixie_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "ear_length",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "short-bob",
    "name": "Short bob",
    "description": "Jaw-length bob with a clean line.",
    "templateId": "all_short_bob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_short_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": []
  },
  {
    "id": "bob-with-fringe",
    "name": "Bob with fringe",
    "description": "Chin-length bob with a full fringe.",
    "templateId": "all_bobcut",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_bobcut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "blunt-bob",
    "name": "Blunt bob",
    "description": "One-length bob with a sharp, blunt edge.",
    "templateId": "female_blunt_bob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_blunt_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": []
  },
  {
    "id": "french-bob",
    "name": "French bob",
    "description": "Short, slightly tousled bob with a fringe.",
    "templateId": "all_french_bob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_french_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "choppy-bob",
    "name": "Choppy bob",
    "description": "Textured, piecey bob.",
    "templateId": "female_choppy_bob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_choppy_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "low",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "tousled-bob",
    "name": "Tousled bob",
    "description": "Loose, undone bob.",
    "templateId": "all_tousled_bob",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_tousled_bob.jpg",
      "salon": "/styles/salon/all_tousled_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "slicked-back-bob",
    "name": "Slicked-back bob",
    "description": "Bob styled back off the face.",
    "templateId": "female_slicked_back_bob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_slicked_back_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "curly-bob",
    "name": "Curly bob",
    "description": "Bob-length curls.",
    "templateId": "female_bobcut_curly",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_bobcut_curly.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "curly",
    "sideEffects": []
  },
  {
    "id": "wavy-bob",
    "name": "Wavy bob",
    "description": "Bob with soft waves.",
    "templateId": "female_bobcut_wavy",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_bobcut_wavy.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "wavy-bob-with-fringe",
    "name": "Wavy bob with fringe",
    "description": "Wavy bob with a fringe.",
    "templateId": "all_wavy_bob_with_bangs",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_wavy_bob_with_bangs.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "mid-part-bob",
    "name": "Mid-part bob",
    "description": "Centre-parted bob just above the shoulders.",
    "templateId": "all_modern_mid_part_bob",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_modern_mid_part_bob.jpg",
      "salon": "/styles/salon/all_modern_mid_part_bob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "low",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": []
  },
  {
    "id": "classic-straight-lob",
    "name": "Classic straight lob",
    "description": "Clean, one-length cut sitting just above the shoulders.",
    "templateId": "female_medium_straight",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_medium_straight.jpg",
      "salon": "/styles/salon/female_medium_straight.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "low",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": []
  },
  {
    "id": "lob-with-fringe",
    "name": "Lob with fringe",
    "description": "Shoulder-grazing lob with a fresh fringe.",
    "templateId": "female_fresh_fringe_lob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_fresh_fringe_lob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "wavy-lob",
    "name": "Wavy lob",
    "description": "Shoulder-grazing lob with loose waves.",
    "templateId": "female_modern_wavy_lob",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_modern_wavy_lob.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "short-feather-cut",
    "name": "Short feather cut",
    "description": "Short, feathered layers.",
    "templateId": "all_short_feather_cut",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_short_feather_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "afro",
    "name": "Afro",
    "description": "Full, rounded afro shape.",
    "templateId": "female_afro",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_afro.jpg"
    },
    "keepUserColor": false,
    "targetLengthBand": "short",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "coily",
    "sideEffects": [
      "changes hair colour"
    ]
  },
  {
    "id": "soft-layered-medium-cut",
    "name": "Soft layered medium cut",
    "description": "Collarbone length with flipped, face-framing layers.",
    "templateId": "all_soft_flipped_layers",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_soft_flipped_layers.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "face-framing-shag",
    "name": "Face-framing shag",
    "description": "Choppy shag layers around the face.",
    "templateId": "all_face_framing_shag_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_face_framing_shag_cut.jpg",
      "salon": "/styles/salon/all_face_framing_shag_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "wavy",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "wavy-shag",
    "name": "Wavy shag",
    "description": "Shag layers with waves.",
    "templateId": "all_wavy_shag",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_wavy_shag.jpg",
      "salon": "/styles/salon/all_wavy_shag.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "wolf-cut",
    "name": "Wolf cut",
    "description": "Heavy layers on top blending into longer ends.",
    "templateId": "all_wolf_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_wolf_cut.jpg",
      "salon": "/styles/salon/all_wolf_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "hush-cut",
    "name": "Hush cut",
    "description": "Soft, airy layers with face framing.",
    "templateId": "all_hush_cut",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_hush_cut.jpg",
      "salon": "/styles/salon/all_hush_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "low",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "medium-curved-layers",
    "name": "Medium curved layers",
    "description": "Medium length with curved-under ends.",
    "templateId": "all_medium_curve_hair",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_medium_curve_hair.jpg",
      "salon": "/styles/salon/all_medium_curve_hair.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "shoulder-length-curtain-waves",
    "name": "Shoulder-length curtain waves",
    "description": "Centre-parted, loose waves around the shoulders.",
    "templateId": "all_curtain_wavy",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_curtain_wavy.jpg",
      "salon": "/styles/salon/all_curtain_wavy.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "loose-waves",
    "name": "Loose waves",
    "description": "Loose, voluminous waves past the shoulders.",
    "templateId": "all_loose_waves",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/all_loose_waves.jpg",
      "salon": "/styles/salon/all_loose_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "gentle-waves",
    "name": "Gentle waves",
    "description": "Soft, subtle waves.",
    "templateId": "all_gentle_waves",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_gentle_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "defined-waves",
    "name": "Defined waves",
    "description": "Structured, defined waves.",
    "templateId": "all_defined_waves",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_defined_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "hollywood-waves",
    "name": "Hollywood waves",
    "description": "Glossy, sculpted vintage waves.",
    "templateId": "all_classic_hollywood_waves",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_classic_hollywood_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "above_chest",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "c-curl-layers",
    "name": "C-curl layers",
    "description": "Long layers with ends curled in a C shape.",
    "templateId": "female_dark_c_curl_layers",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_dark_c_curl_layers.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "any",
    "sideEffects": []
  },
  {
    "id": "beachy-waves",
    "name": "Beachy waves",
    "description": "Long, relaxed, beach-style texture.",
    "templateId": "all_beachy",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_beachy.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "bouncy-curls",
    "name": "Bouncy curls",
    "description": "Long, voluminous, bouncy curls.",
    "templateId": "female_bouncy_curls",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_bouncy_curls.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "high",
    "commitment": "medium",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "curly",
    "sideEffects": []
  },
  {
    "id": "straight-with-blunt-fringe",
    "name": "Straight with blunt fringe",
    "description": "Long, straight hair with a blunt fringe.",
    "templateId": "female_blunt_fringe_straight",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_blunt_fringe_straight.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "long-straight-with-fringe",
    "name": "Long straight with fringe",
    "description": "Long, sleek length with a full fringe.",
    "templateId": "female_long_straight",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/female_long_straight.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": [
      "adds a fringe"
    ]
  },
  {
    "id": "side-part-straight",
    "name": "Side-part straight",
    "description": "Long, straight hair with a side part.",
    "templateId": "female_side_part_straight",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_side_part_straight.jpg",
      "salon": "/styles/salon/female_side_part_straight.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": false,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": []
  },
  {
    "id": "long-soft-waves",
    "name": "Long soft waves",
    "description": "Long hair with soft waves.",
    "templateId": "female_long_wavy",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_long_wavy.jpg",
      "salon": "/styles/salon/female_long_wavy.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "long-boho-waves",
    "name": "Long boho waves",
    "description": "Long, relaxed boho waves.",
    "templateId": "female_long_boho_waves",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_long_boho_waves.jpg",
      "salon": "/styles/salon/female_long_boho_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "romantic-waves",
    "name": "Romantic waves",
    "description": "Long, soft romantic waves.",
    "templateId": "all_romantic_waves",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_romantic_waves.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "high",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "wavy",
    "sideEffects": []
  },
  {
    "id": "long-spiral-curls",
    "name": "Long spiral curls",
    "description": "Long, defined spiral curls.",
    "templateId": "female_long_spiral_curls",
    "collections": [
      "barbershop",
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "barbershop": "/styles/barbershop/female_long_spiral_curls.jpg",
      "salon": "/styles/salon/female_long_spiral_curls.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "high",
    "commitment": "high",
    "textureSensitive": true,
    "requiresStylistConfirmation": false,
    "mayNeedChemical": true,
    "textureNeed": "curly",
    "sideEffects": []
  },
  {
    "id": "hime-cut",
    "name": "Hime cut",
    "description": "Long hair with blunt cheek-length side sections.",
    "templateId": "all_hime_cut",
    "collections": [
      "salon"
    ],
    "home": "salon",
    "thumbs": {
      "salon": "/styles/salon/all_hime_cut.jpg"
    },
    "keepUserColor": true,
    "targetLengthBand": "long",
    "maintenance": "medium",
    "commitment": "high",
    "textureSensitive": false,
    "requiresStylistConfirmation": true,
    "mayNeedChemical": false,
    "textureNeed": "straight",
    "sideEffects": [
      "adds a fringe"
    ]
  }
];

export const CATALOG: TargetStyle[] = ROWS.map((r) => ({ ...r, routeHints: routeHintsFor(r) }));

export function getStyle(id: string): TargetStyle | undefined {
  return CATALOG.find((s) => s.id === id);
}

export function stylesIn(collection: Collection | "all"): TargetStyle[] {
  return collection === "all" ? CATALOG : CATALOG.filter((s) => s.collections.includes(collection));
}

/** Example picture for a style on the shelf being browsed (falls back to its first shelf). */
export function thumbFor(s: TargetStyle, collection: Collection | "all"): string | undefined {
  if (collection !== "all" && s.thumbs[collection]) return s.thumbs[collection];
  return s.thumbs[s.collections[0]] ?? Object.values(s.thumbs)[0];
}
